{
  Class<?> testClass=prepareTest();
  try {
    testClass.getMethod("foo",Object.class,Object.class).invoke(testClass.newInstance(),null,null);
    fail();
  }
 catch (  InvocationTargetException e) {
    assertInstanceOf(e.getCause(),NullPointerException.class);
    assertEquals("Argument 1 for @NotNull parameter of CustomExceptionType.foo must not be null",e.getCause().getMessage());
  }
}
