{
  doTestFailure(PyBundle.message("refactoring.make.function.top.level.error.special.usage.of.self"));
}
