{
  myRepository.setPassword("wrong-password");
  try {
    final Exception exception=myRepository.createCancellableConnection().call();
    assertNotNull("Test connection must fail when wrong credentials specified",exception);
  }
 catch (  Exception e) {
    assertEquals(TaskBundle.message("failure.login"),e.getMessage());
  }
}
