{
  if (!force)   return;
  try {
    ourFuture.get();
  }
 catch (  Exception e) {
    LOG.warn(e);
  }
}
