{
  try {
    return action.apply();
  }
 catch (  InterruptedException x) {
    final InterruptedIOException y=new InterruptedIOException(x.getMessage());
    y.initCause(x);
    throw y;
  }
}
