{
  super("try","try { exp } catch(Exception e)");
}
