{
  A.FooException exception=new A.FooException("");
}
