{
  final Throwable cause=exception.getCause();
  if (cause instanceof VagrantNotStartedException) {
    final String vagrantFolder=((VagrantNotStartedException)cause).getVagrantFolder();
    return new PyExecutionException(command,args,"Vagrant instance is down",ImmutableList.of(new LaunchVagrantFix(vagrantFolder)));
  }
  return exception;
}
