{
  if (!future.isSuccess()) {
    Throwable cause=future.cause();
    setError(cause == null ? Promise.createError("No success") : cause);
  }
}
